
all: cpp-list cpp-list2 cpp-list3

file: file.cc

cpp-list: cpp-list.cc
	g++ -g -o cpp-list cpp-list.cc

cpp-list2: cpp-list2.cc
	g++ -g -o cpp-list2 cpp-list2.cc

cpp-list3: cpp-list3.cc
	g++ -g -o cpp-list3 cpp-list3.cc

clean:
	rm -f cpp-list perms file cpp-list2 cpplist-3

.PHONY: clean
